apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
#SVC-BEGIN
  - service.yaml
#SVC-END
configMapGenerator:
  - name: __APP__
    envs:
      - config.env
labels:
  - pairs:
      app.kubernetes.io/name: hellnet-service
      app.kubernetes.io/instance: __APP__
    includeSelectors: false
