apiVersion: v1
kind: Service
metadata:
  name: __APP__
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: hellnet-service
    app.kubernetes.io/instance: __APP__
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
