issuer: https://token.actions.githubusercontent.com
subject_pattern: 'repo:guilhermelinosp@121059870/templates@[0-9]+:.*'
claim_pattern:
  job_workflow_ref: 'guilhermelinosp/templates/\.github/workflows/release\.yml@.*'
permissions:
  contents: write
