name: sbom

# SBOM generation with Anchore Syft
# Inputs: image, format (default: spdx-json)

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      format:
        required: false
        default: "spdx-json"
        type: string

permissions:
  contents: read
  packages: read

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Generate SBOM
        uses: anchore/sbom-action@v0.24.3
        with:
          image: ${{ inputs.image }}
          format: ${{ inputs.format }}
          output-file: sbom.${{ inputs.format }}

      - name: Upload SBOM
        uses: actions/upload-artifact@v7
        with:
          name: sbom
          path: sbom.${{ inputs.format }}
