name: sbom

# SBOM generation with Anchore Syft
# Inputs: image, format (default: spdx-json)

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      format:
        required: false
        default: "spdx-json"
        type: string

permissions:
  contents: read
  packages: read

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Generate SBOM
        uses: anchore/sbom-action@3ad7283483fc7af8ff2b4ea19663c2d5ca935e26
        with:
          image: ${{ inputs.image }}
          format: ${{ inputs.format }}
          output-file: sbom.${{ inputs.format }}

      - name: Upload SBOM
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: sbom
          path: sbom.${{ inputs.format }}
